= Woots PowerShell

== Abstract

Op deze Github vind je een PowerShell module voor het interfacing met Woots Web API v2. Dit is gebaseerd op de https://app.woots.nl/api/docs/index.html#/[Woots API documentatie].


== Gebruik

De module bestaat uit twee bestaden:  ``Woots.ps1`` en  ``Woots-generatedcode.ps1``. Download beide bestanden in je werkmap. 
Je kunt de module in je scripts gebruiken door de module te importeren bijvoorbeeld als volgt.

[source,PowerShell]
----
Import-Module .\Woots.ps1
----
of 
[source,PowerShell]
----
Import-Module "$PSScriptRoot\Woots.ps"
----

Initializeer Woots door een aanroep naar ``Initialize-Woots``. Deze functie verwacht 3 parameters:
* ``$Hostname``  : dit is de hostname van het endpoint, meestal 'app.woots.nl' . Dit wordt aangevuld tot 'https://app.woots.nl/api/v2'.
* ``$School_id`` : numerieke ID van de school.
* ``$Token`` : een string met het authorizatietoken voor de web API.


== Documentatie 

Werp een blik op de functiedefinities in ``Woots-generatedCode.ps1`` om te zien welke functies er allemaal gedefinieerd zijn. 


=== Standaard Functieparameters

Alle functies slechts één of meer van de volgende parameters. 


* ``$Id`` : het numeriek ID van de resource waarop de bewerking betrekking heeft (alle functies van de categorie Get-Resource, Get-ResourceItem, Set-Resource, Add-ResourceItem, Remove-Resource).

* ``$Parameter`` : een hastable met de in te stellen attributen van een resource (alle functies van de categorie Add-Resource, Add-ResourceItem, Set-Resource, Set-ResourceItem), of een hashtable met naam-waarde-paren die het filter definieren voor een zoekactie (alle functies van de categorie Search-Resource).

* ``$MaxItems`` : een getal , dat indien groter dan 0, het hoogste aantal items aangeeft, dat moeten worden opgehaald. Bij weglating van deze parameter of bij een negatieve waarde, wordt het maximum aantal beschikbare items geretourneerd (alle functies van de categorie Search-Resource, Get-AllResources).

Alle parameters zijn PowerShell objecten, behalve waar het gaat om booleaanse waarden; in dat geval volstaat de string ``"false"`` of ``"true"``. 

Voorbeeld: 

----
$filter = @{ 
    name = "Aardrijkskunde"
    trashed = "false"
}
$result = Search-WootsCourse -Parameter $filter
----

== Extra's 

Een deel van de code in de module is gegenereerd door een codegenerator. 
* ``WootsModuleCodeGenerator.ps1`` : dit script genereert de code in ``Woots-generatedcode.ps1``. 
* ``Woots-api-calls.csv`` : dit bestand wordt ingelezen door ``WootsModuleCodeGenerator.ps1``. 
